export const testWiki = [
  { _id: '1', name: 'result1', revision: '1' },
  { _id: '2', name: 'result2', revision: '1' },
  { _id: '3', name: 'result3', revision: '1' },
  { _id: '4', name: 'result4', revision: '1' },
  { _id: '5', name: 'result5', revision: '1' },
  { _id: '6', name: 'result6', revision: '1' },
  { _id: '7', name: 'result7', revision: '1' },
  { _id: '8', name: 'result8', revision: '1' },
  { _id: '9', name: 'result9', revision: '1' },
  { _id: '10', name: 'result10', revision: '1' },
];
export const testPost = [
  {
    _id: 'p1',
    title: 'PostResult1',
    publisher: 'test01',
    publishedDate: Date.now(),
    tags: ['testTag', 'testTag2'],
  },
  {
    _id: 'p2',
    title: 'PostResult2',
    publisher: 'test01',
    publishedDate: Date.now(),
    tags: ['testTag'],
  },
  {
    _id: 'p3',
    title: 'PostResult3',
    publisher: 'test01',
    publishedDate: Date.now(),
    tags: ['testTag'],
  },
  {
    _id: 'p4',
    title: 'PostResult4',
    publisher: 'test01',
    publishedDate: Date.now(),
    tags: ['testTag'],
  },
  {
    _id: 'p5',
    title: 'PostResult5',
    publisher: 'test01',
    publishedDate: Date.now(),
    tags: ['testTag'],
  },
  {
    _id: 'p6',
    title: 'PostResult6',
    publisher: 'test01',
    publishedDate: Date.now(),
    tags: ['testTag'],
  },
  {
    _id: 'p7',
    title: 'PostResult7',
    publisher: 'test01',
    publishedDate: Date.now(),
    tags: ['testTag'],
  },
  {
    _id: 'p8',
    title: 'PostResult8',
    publisher: 'test01',
    publishedDate: Date.now(),
    tags: ['testTag'],
  },
  {
    _id: 'p9',
    title: 'PostResult9',
    publisher: 'test01',
    publishedDate: Date.now(),
    tags: ['testTag'],
  },
  {
    _id: 'p10',
    title: 'PostResult10',
    publisher: 'test01',
    publishedDate: Date.now(),
    tags: ['testTag'],
  },
];
